### ISSUE TITLE
Can't I run with system privileges?

### ISSUE THREAD

**Issue by ttsite** [ZeroMemoryEx/Terminator#6]
I create a system service and then run this program using the system service, but it cannot be executed. I don't know why, or is the program unable to run as a system service?

**Comment by ZeroMemoryEx** [comment]
no need to execute it as SYSTEM privilege, you only need administrator privilege , just left click and run it as administrator and let the rest to it

**Comment by illegal-instruction-co** [comment]
For best experience, use it with https://github.com/hfiref0x/UACME Akagi64. Based on this approach, you will not needed to administrator privilege as well.

**Comment by ZeroMemoryEx** [comment]
although no need for SYSTEM privilege to execute the program, all needed is **SeLoadDriverPrivilege** or admin privilege

**Comment by ZeroMemoryEx** [comment]
NT AUTHORITY you have all rights enabled so yeah, you can load the driver fluently
