### ISSUE TITLE
Cleaning steps

### ISSUE THREAD

**Issue by Kn0xsec** [ZeroMemoryEx/Terminator#8]
Just curious about the best way to remove the loaded driver and exe after use. I noticed that the exe may be deleted after use, but the associated driver (Terminator.sys) cannot, and I'm wondering what is the best approach to entirely remove it.

**Comment by ZeroMemoryEx** [comment]
Hello, I think I forgot to add a feature to unload the driver, Although it's easy to unload, you can simply go to the task manager, then navigate to services and stop the service or type the following command in cmd

`sc stop Terminator
`

**Comment by Kn0xsec** [comment]
Great, thanks! I attempted to delete the driver file manually after use but received a "Access Denied" message every time since the driver might be loaded into the system, hence I thought about asking for the best approach to remove it.

**Comment by ZeroMemoryEx** [comment]
hello @Kn0xsec  run the command as administrator

**Comment by Kn0xsec** [comment]
Will do, thanks! Also, curious to know if you used the same (zam64.sys) loldriver described in the repository or if you modified it?

**Comment by ZeroMemoryEx** [comment]
Hello @Kn0xsec , yes, I used the same one in Loldriver. I only changed the name because patching it or changing anything would invalidate its signature, thus making it unusable.

**Comment by Kn0xsec** [comment]
Thanks for the confirmation!
