### ISSUE TITLE
Device handle leaked in error path

### ISSUE THREAD

**Issue by JohnLaTwC** [ZeroMemoryEx/Terminator#9]
Device handle leaked in error path

```diff
	if (!DeviceIoControl(hDevice, IOCTL_REGISTER_PROCESS, &input, sizeof(input),
		NULL, 0, NULL, NULL)) {
		printf("Failed to register the process in the trusted list %X !!\n",
			IOCTL_REGISTER_PROCESS);
+		CloseHandle(hDevice);
		return (-1);
	}
```

https://github.com/ZeroMemoryEx/Terminator/blob/1d91049d562cfa69d4102f4fc3637a861a7fe873/Terminator/Terminator.cpp#L214

**Comment by ZeroMemoryEx** [comment]
Hello @JohnLaTwC , thank you for reporting this bug. I will fix it in the next update!!

**Comment by ZeroMemoryEx** [comment]
thank you fixed in [commit](https://github.com/ZeroMemoryEx/Terminator/commit/a844482c947f29c345c3bfd333958d09bdd789fc)
